version: '3.8'

services:
  elite-resume-builder:
    build: .
    ports:
      - "5000:5000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - FLASK_ENV=development
      - PORT=5000
    volumes:
      - .:/app
    restart: unless-stopped
